global:
  scrape_interval: 15s
  external_labels:
    cluster: "test-cluster"
    prometheus: "prometheus-main"
    environment: "test"

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']